version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: rxcirrhose/app
    ports:
      - "8080:80"
    networks:
      - rxcirrhose
    volumes:
      - ./:/var/www/html
    env_file: .env
networks:
  rxcirrhose:
